controller_list:
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_4
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
initial:  # Define initial robot poses per group
  - group: hand
    pose: hand_close
  - group: arm_group
    pose: zero_pose